# Week of 2024-07-15 to 2024-07-22 (38)

### GHFirst (14)

- [Revert "Invalidate StorageImpl instances when tensor is overwritten with cudagraphs (#125264)"](https://github.com/pytorch/pytorch/commit/7c299b46ca4d056835f7da0d6950939106469edb)
  - breaks internal tests ([comment](https://github.com/pytorch/pytorch/pull/125264#issuecomment-2240516202))
- [Revert "[easy][pytorch][counters] Move WaitCounter in c10/util (#131021)"](https://github.com/pytorch/pytorch/commit/0e72baddf0b863b853cbbd509f5229e3bf7ed2ef)
  - Diff reverted internally ([comment](https://github.com/pytorch/pytorch/pull/131021#issuecomment-2240280827))
- [Revert "[ROCm] Enable ROCm support for inductor's dynamic_rblock_scaling  (#129663)"](https://github.com/pytorch/pytorch/commit/5f981388ec45d4dab3575dd79f9f6dad79cbce52)
  - Breaks internal builds ([comment](https://github.com/pytorch/pytorch/pull/129663#issuecomment-2240011143))
- [Revert "[c10] add an option to pg_config split share (#130877)"](https://github.com/pytorch/pytorch/commit/5f3d8b87886499b49503bbaf8db4c152f714ea5e)
  - breaks internal build ([comment](https://github.com/pytorch/pytorch/pull/130877#issuecomment-2239298810))
- [Revert "Re-implement pin_memory to be device-agnostic by leveraging the Accelerator concept (#126376)"](https://github.com/pytorch/pytorch/commit/726b9268d24382e8146a8395fa60304134b2b1e6)
  - Failing internal builds ([comment](https://github.com/pytorch/pytorch/pull/126376#issuecomment-2237496633))
- [Revert "Use inductor TestCase for test_replicate_with_compiler.py (#129494)"](https://github.com/pytorch/pytorch/commit/fff92d4f18f1dfb22782d957fb003472e11a76e2)
  - broke internal tests ([comment](https://github.com/pytorch/pytorch/pull/129494#issuecomment-2237147504))
- [Revert "Ensure staticmethods can be allowed in graph (#130882)"](https://github.com/pytorch/pytorch/commit/9f6db5d0e23d4e458bf011c9c77b0d85d6306805)
  - failing torchrec tests internally, please fix and reland ([comment](https://github.com/pytorch/pytorch/pull/130882#issuecomment-2236528473))
- [Revert "Renamed mask_fn to mask_mod (#130818)"](https://github.com/pytorch/pytorch/commit/94a910b43b5c10e101f7ef863f457bba19305822)
  - Failing internally ([comment](https://github.com/pytorch/pytorch/pull/130818#issuecomment-2233367318))
- [Revert "Removed q_num_blocks from constructor (#130819)"](https://github.com/pytorch/pytorch/commit/d027aef8f86bd70c4ae525fc1bef92f1301e71c2)
  - Internal problem with previous PR in stack https://github.com/pytorch/pytorch/pull/130818 ([comment](https://github.com/pytorch/pytorch/pull/130819#issuecomment-2233359569))
- [Revert "[cuDNN][SDPA] Support `attn_bias` in cuDNN (#130482)"](https://github.com/pytorch/pytorch/commit/e1b2d8f975b1ee4eb1ffc0afdc2e9e462b11d794)
  - failing internally ([comment](https://github.com/pytorch/pytorch/pull/130482#issuecomment-2233309217))
- [Revert "[PT-D] Relaxed `contract` to allow `Sequence[nn.Module]` (#127773)"](https://github.com/pytorch/pytorch/commit/d7a8e8f7c5a0a536cecf397561d161d8576e9574)
  - failing internally ([comment](https://github.com/pytorch/pytorch/pull/127773#issuecomment-2232004006))
- [Revert "[FSDP2] Allowed `List[nn.Module]` as arg (#127786)"](https://github.com/pytorch/pytorch/commit/4f40a7078ef47cb9fb841df07766a5a7b530bf1f)
  - bottom pr from the stack is failing on internal error ([comment](https://github.com/pytorch/pytorch/pull/127786#issuecomment-2231999178))
- [Revert "Tighten torch.library.infer_schema input types (#130705)"](https://github.com/pytorch/pytorch/commit/68a4f2a3df3d095ce91ff40f3dea8ad92d76e9e0)
  - Failing internal CI ([comment](https://github.com/pytorch/pytorch/pull/130705#issuecomment-2230821876))
- [Revert "Constant folding for dynamic shape node (#129686)"](https://github.com/pytorch/pytorch/commit/9df4bc6a0dc72caccee142555d1668fad1621206)
  - Failing internally.  Test: https://github.com/pytorch/ao/blob/main/test/prototype/mx_formats/test_mx_linear.py ([comment](https://github.com/pytorch/pytorch/pull/129686#issuecomment-2228755295))

### Ignored Signal (7)

- [Revert "Define key in codecache (#130979)"](https://github.com/pytorch/pytorch/commit/874bbc53c9dfdf108e8a8af63109c06f9ff7f6e4)
  - broke lint on torch/_inductor/codecache.py https://github.com/pytorch/pytorch/actions/runs/9981737836/job/27586013811 https://hud.pytorch.org/pytorch/pytorch/commit/f0faecd2915d73e56917922cc995237cef064e50 ([comment](https://github.com/pytorch/pytorch/pull/130979#issuecomment-2234392332))
- [Revert "Relax constraints for creating a `GenericContextWrappingVariable` (#129091)"](https://github.com/pytorch/pytorch/commit/0b134c15cdf8cb4c2c7ffed1c2b6518de44382bf)
  - test_jit started failing on main after this stack https://github.com/pytorch/pytorch/actions/runs/9980754603/job/27583474357 https://hud.pytorch.org/pytorch/pytorch/commit/a8bd2933d9eaf24ec9582001efa844de499d9e93 ([comment](https://github.com/pytorch/pytorch/pull/129091#issuecomment-2234269541))
- [Revert "wrap self.call_function(...) in try finally block to undo changes to self.kw_names (#130490)"](https://github.com/pytorch/pytorch/commit/c49f909aab0a8e909b901688dbb9b57f5aaa9b86)
  - test_jit started failing on main after this stack https://github.com/pytorch/pytorch/actions/runs/9980754603/job/27583474357 https://hud.pytorch.org/pytorch/pytorch/commit/a8bd2933d9eaf24ec9582001efa844de499d9e93 ([comment](https://github.com/pytorch/pytorch/pull/129091#issuecomment-2234269541))
- [Revert "[inductor] adapte windows file path (#130713)"](https://github.com/pytorch/pytorch/commit/5f3c356a56ebb2d4b746a9e2312b9e551aeda90e)
  - broke functorch\test_eager_transforms.py on windows https://github.com/pytorch/pytorch/actions/runs/9958208725/job/27530132704 https://hud.pytorch.org/pytorch/pytorch/commit/69e99172450e40536bf2e6c110183d34a0e283e2.  Test failure on PR is real, possibly force merged to get around lint error? ([comment](https://github.com/pytorch/pytorch/pull/130713#issuecomment-2231901793))
- [Revert "[Traceable FSDP2][Inductor] Re-inplace all_gather_into_tensor (#129773)"](https://github.com/pytorch/pytorch/commit/c1e7e40f246ece1c402c11e7ac049dcdaaf6b93a)
  - failed inductor/test_torchinductor_dynamic_shapes.py on mac https://github.com/pytorch/pytorch/actions/runs/9963396991/job/27530249256 https://hud.pytorch.org/pytorch/pytorch/commit/f2f31027ce8dc3985663bf6eaa66f3c5559b724a.  The build failed on PR so test jobs didn't run ([comment](https://github.com/pytorch/pytorch/pull/129773#issuecomment-2231808437))
- [Revert "[BE] bump `optree` version to 0.12.1 (#130139)"](https://github.com/pytorch/pytorch/commit/074a5c0c9b94cb3708e3ce77e8869b0ae77b4701)
  - broke inductor/test_torchinductor_codegen_dynamic_shapes.py and test_sympy_utils.py https://hud.pytorch.org/pytorch/pytorch/commit/8fcb156e8b5697a8f292db6db2a1803c5f4ce2d7 ([comment](https://github.com/pytorch/pytorch/pull/130139#issuecomment-2229248447))
- [Revert " [5/N] Change static functions in headers to inline  (#130673)"](https://github.com/pytorch/pytorch/commit/c0897919dac774214a6b3cc70af80e365028144c)
  - Sorry for reverting your change but it causes CUDA build 12.1/12.4 to timeout in trunk, I am not sure what I am looking at yet, so attempt to revert to see if it fixes trunk.  Plz keep in mind that a cancelled job is counted as a failure ([comment](https://github.com/pytorch/pytorch/pull/130673#issuecomment-2227641368))

### Landrace (10)

- [Revert "[Autograd] Cond Higher-Order Operation (#126911)"](https://github.com/pytorch/pytorch/commit/fb3674b1f48952dba8f35729757b7579b1ff1583)
  - broke lint and functorch/test_aotdispatch https://hud.pytorch.org/pytorch/pytorch/commit/f7058b735e52a1d876912f8c96a594673a495007 Probably a landrace since both the test and lint passed on PR ([comment](https://github.com/pytorch/pytorch/pull/126911#issuecomment-2237703182))
- [Revert "[aota] Needs autograd if an input requires_grad, agnostic to enable_grad (#128890)"](https://github.com/pytorch/pytorch/commit/120fdf7ee21f79a0990f0e769c0c95c8d0c4614c)
  - broke trunk tests, probably a landrace ([comment](https://github.com/pytorch/pytorch/pull/128890#issuecomment-2236790805))
- [Revert "[BE][Easy][12/19] enforce style for empty lines in import segments in `test/i*/` (#129763)"](https://github.com/pytorch/pytorch/commit/b732b52f1e4378f8486ceb5e7026be3321c2651c)
  - need reland after rerunning lintrunner on main ([comment](https://github.com/pytorch/pytorch/pull/129763#issuecomment-2235736732))
- [Revert "[FX][export] DCE pass, check schema for node impurity (#130395)"](https://github.com/pytorch/pytorch/commit/433ef4e4443af4d1921ccd6cd49fb2253481b58c)
  - breaking tests, need to rebase and fix ([comment](https://github.com/pytorch/pytorch/pull/130395#issuecomment-2235192986))
- [Revert "[ts-migration] Support RaiseException, prim::Unitialized, prim::Enter, and prim::Exit (#129416)"](https://github.com/pytorch/pytorch/commit/1bf4a44b335b53ba9f9c7056a54ed8e4010e561b)
  - broke lint for test/export/test_converter.py https://github.com/pytorch/pytorch/actions/runs/9979009143/job/27577181982 https://hud.pytorch.org/pytorch/pytorch/commit/ef0511245a92bae7057c195dcae2efc237b96f16.  Probably a landrace ([comment](https://github.com/pytorch/pytorch/pull/129416#issuecomment-2234067407))
- [Revert "Propagate buffer and parameter indices through AOT (#130393)"](https://github.com/pytorch/pytorch/commit/cbda8be537fc2c49220e1d14d2505cb38d5fa832)
  - broke lint for torch/_functorch/_aot_autograd/subclass_utils.py https://github.com/pytorch/pytorch/actions/runs/9948630877/job/27483551649 https://hud.pytorch.org/pytorch/pytorch/commit/80236dca90b0874cb2b6f9c9fa5f159c55726401 lint was green on PR, probably a landrace ([comment](https://github.com/pytorch/pytorch/pull/130393#issuecomment-2231263753))
- [Revert "Add buffer static input tests to cudagraph trees (#130402)"](https://github.com/pytorch/pytorch/commit/9cb23ba85b0681330a32e6df277ec07fb105af38)
  - broke lint for torch/_functorch/_aot_autograd/subclass_utils.py https://github.com/pytorch/pytorch/actions/runs/9948630877/job/27483551649 https://hud.pytorch.org/pytorch/pytorch/commit/80236dca90b0874cb2b6f9c9fa5f159c55726401 lint was green on PR, probably a landrace ([comment](https://github.com/pytorch/pytorch/pull/130393#issuecomment-2231263753))
- [Revert "Fix names conflict when lifting (#129817)"](https://github.com/pytorch/pytorch/commit/dff9d68f1878ec3e8e34a90376feef6cc3e9019b)
  - Failing inductor/test_flex_attention.py https://github.com/pytorch/pytorch/actions/runs/9940532858/job/27478084137 https://hud.pytorch.org/pytorch/pytorch/commit/74da2a467f166e00316aee82ba24835ca563ed87 Sorry for the churn, possibly a landrace? ([comment](https://github.com/pytorch/pytorch/pull/129817#issuecomment-2229519886))
- [Revert "Invalidate StorageImpl instances when tensor is overwritten with cudagraphs (#125264)"](https://github.com/pytorch/pytorch/commit/78799e82b06d36753e6d1dbbb644f387cd299364)
  - test test/inductor/test_cudagraph_trees.py::CudaGraphTreeTests::test_fallback_to_eager_if_recompiling_too_many_times is failing https://github.com/pytorch/pytorch/actions/runs/9933628108/job/27477785946 https://hud.pytorch.org/pytorch/pytorch/commit/1bc390c5f5ac065c156f55f4eceed267ecc67b41. Test was introduced by https://github.com/pytorch/pytorch/commit/fa5f5727484d78aa2ed8668c11550431bd415f5c which is before the merge base ([comment](https://github.com/pytorch/pytorch/pull/125264#issuecomment-2229508737))
- [Revert "Fix names conflict when lifting (#129817)"](https://github.com/pytorch/pytorch/commit/1e897a0ca4467dfb16e91e2b67252aea7522878d)
  - False alarm your commit just got really unlucky sorry ~broke dynamo/test_inline_inbuilt_nn_modules.py https://github.com/pytorch/pytorch/actions/runs/9940532858/job/27461141919 https://hud.pytorch.org/pytorch/pytorch/commit/74da2a467f166e00316aee82ba24835ca563ed87.  Test passed on PR, possibly a landrace?~ ([comment](https://github.com/pytorch/pytorch/pull/129817#issuecomment-2228993570))

### No Signal (2)

- [Revert "[inductor] adapte windows file path (#130713)"](https://github.com/pytorch/pytorch/commit/41f5d5dcafb1b4612ca00ea69da490c03eba5349)
  - sorry but I think its still failing, this time on windows CUDA https://github.com/pytorch/pytorch/actions/runs/9971126834/job/27552761451 https://hud.pytorch.org/pytorch/pytorch/commit/bb62e9d7c3e4c4de6c84b37479372024a048b0b6.  It was not run on PR due to being on the periodic workflow, which isnt usually run on PRs due to capacity issues for windows CUDA machines.  I will add ciflow/periodic to the PR to ensure the test gets run ([comment](https://github.com/pytorch/pytorch/pull/130713#issuecomment-2234092078))
- [Revert "Use inductor TestCase for distributed tests (#129494)"](https://github.com/pytorch/pytorch/commit/8458dc8966dc4946df67700300455b2c73c46de6)
  - fbcode failures ([comment](https://github.com/pytorch/pytorch/pull/129494#issuecomment-2232063690))

### Weird (5)

- [Revert "[executorch hash update] update the pinned executorch hash (#130001)"](https://github.com/pytorch/pytorch/commit/30d1826b2bda94112d39e4af9393727f1d1290dd)
  - the test_sympy_utils failure is real, Dr. CI is wrong https://github.com/pytorch/pytorch/actions/runs/10015433275/job/27687163560 https://hud.pytorch.org/pytorch/pytorch/commit/4821f72457afd7b1b5c61c1c8c3c49105c1bd22d ([comment](https://github.com/pytorch/pytorch/pull/130001#issuecomment-2240807631))
- [Revert "[export] Add print_readable to unflattener (#128617)"](https://github.com/pytorch/pytorch/commit/d6ae8bbf16e8a974cadc1422c83ca29a5223e50f)
  - broke inductor/test_flex_attention https://github.com/pytorch/pytorch/actions/runs/9984688318/job/27595182606 https://hud.pytorch.org/pytorch/pytorch/commit/433ef4e4443af4d1921ccd6cd49fb2253481b58c Not run on PR due to bad TD ([comment](https://github.com/pytorch/pytorch/pull/128617#issuecomment-2236867975))
- [Revert "[ts-migration] Support RaiseException, prim::Unitialized, prim::Enter, and prim::Exit (#129416)"](https://github.com/pytorch/pytorch/commit/0eb43ed18952d9e44a098acad602868694e239da)
  - Lintrunner started breaking on incorrect commit ~broke lint, but for for torch/_inductor/codecache.py this time https://github.com/pytorch/pytorch/actions/runs/9981737836/job/27586013811 https://hud.pytorch.org/pytorch/pytorch/commit/f0faecd2915d73e56917922cc995237cef064e50~ ([comment](https://github.com/pytorch/pytorch/pull/129416#issuecomment-2234387254))
- [Revert "[ONNX] Remove beartype usage (#130484)"](https://github.com/pytorch/pytorch/commit/0851de5b167d3856285ad2a370c0355453d328dc)
  - test_sympy_utils failure is real https://github.com/pytorch/pytorch/actions/runs/9961499559/job/27523758780 https://hud.pytorch.org/pytorch/pytorch/commit/1794c35912025aa44b0d70f67ff664b4f7bd1014.  Dr CI found a match on a different PR but you guys just happen to break the same test, and I think this test was broken on main very briefly too ([comment](https://github.com/pytorch/pytorch/pull/130484#issuecomment-2231575577))
- [Revert "Increase tolerance for tensorsolve tests (#130620)"](https://github.com/pytorch/pytorch/commit/9e161af179a781acfb839942aacb12c1f09395af)
  - didn't work, test is still failing on this PR and on main, reverting in favor of https://github.com/pytorch/pytorch/pull/130449 instead ([comment](https://github.com/pytorch/pytorch/pull/130620#issuecomment-2229036418))
